### ISSUE TITLE
Extension: error message

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTFlows.jl#28]
@ocots according to the weak dep. in `Project.toml`, using `OrdinaryDiffEq.jl` (lighter than `DifferentialEquations.jl`) is enough. Am I missing sth? If not, can you please update the message below?

![IMG_3314](https://github.com/control-toolbox/CTFlows.jl/assets/62183989/2de89af9-4e26-454b-83e8-b8aa9b69d359)

**Comment by ocots** [comment]
I have made the modification.

**Comment by ocots** [comment]
See

https://github.com/control-toolbox/CTFlows.jl/blob/072356af88a52ff9f4210793cdb703563b4448a2/src/CTFlows.jl#L26
